### ISSUE TITLE
Cannot control Sawyer gripper's holding force

### ISSUE THREAD

**Issue by YurongYou** [RethinkRobotics/intera_sdk#103]
Hi, I ran the [gripper example](https://github.com/RethinkRobotics/intera_sdk/blob/master/intera_examples/scripts/gripper_keyboard.py), but I fould that I could not control its gripping force. The error message is 
```
[ERROR] [WallTime: 1499118804.154082] Cannot find signal 'holding_force_n' in this IO Device.
```
And after I did `rostopic echo /io/end_effector/right_gripper/config`, it turned out that there was indeed not a signal named 'holding_force_n'. 
What's wrong with it?

P.S. Is there any documentation describing how the gripper is controlled (e.g. force control / position control etc.)?

**Comment by IanTheEngineer** [comment]
@YurongYou, apologies for the delayed response here. After investigating this further, it turns out the Embedded team at Rethink needed to remove this signal in the 5.1 update. It escaped my knowledge, and as such I left in the interface here. I remedy this in the upcoming 5.2 update by removing the interface.

While I generally dislike removing interfaces, I can understand the need for such action in this circumstance: increasing the "holding_force" value, beyond the default 30% increased the possibility of jamming the gripper dramatically. This is something we experienced quite a bit when using the electric gripper on Baxter.

As for gripper documentation, it is sparse, but I will make an effort to add an end effector page on the [wiki](http://sdk.rethinkrobotics.com/intera/Main_Page) for this release. It is a position controlled gripper.
